<script lang="ts">
  import { untrack } from "svelte";
  import { nativeMedia } from "../lib/native-media";
  let { value }: { value?: unknown } = $props();
  let current = $state(untrack(() => value));
  export function update(next: unknown): void { current = next; }
  const media = $derived(nativeMedia(value === undefined ? current : value));
  const preview = $derived(media?.previewDataUrl);
  let failed = $state(false);
  let dialog = $state<HTMLDialogElement>();
  $effect(() => { preview; failed = false; untrack(() => dialog?.close()); });
</script>

{#if media}
  <figure class="native-media">
    {#if media.state === "ready" && !failed}
      <button class="preview" type="button" aria-label="Enlarge generated image" onclick={() => dialog?.showModal()}>
        <img src={media.previewDataUrl} width={media.width} height={media.height} alt="Generated by Codex" onerror={() => failed = true} />
      </button>
      <figcaption>{media.label} · {media.width} × {media.height} · Click to enlarge</figcaption>
    {:else}<figcaption role="status">{failed ? "This image could not be decoded. The original result remains in native Codex history." : media.label}</figcaption>{/if}
  </figure>
  <dialog bind:this={dialog} aria-label="Generated image preview">
    <button type="button" onclick={() => dialog?.close()}>Close preview</button>
    {#if media.state === "ready" && !failed}<img src={media.previewDataUrl} width={media.width} height={media.height} alt="Generated by Codex, enlarged" onerror={() => failed = true} />{/if}
  </dialog>
{/if}

<style>
  .native-media {margin:var(--ca-space-3) 0;min-width:0;}
  .preview {display:block;width:100%;padding:0;cursor:zoom-in;}
  img {display:block;max-width:100%;height:auto;object-fit:contain;border-radius:var(--ca-control-radius);}
  .preview img {max-height:60vh;}
  figcaption {margin-top:var(--ca-space-2);color:var(--ca-muted);font:var(--ca-type-caption)/var(--ca-leading-body) var(--ca-font-body);overflow-wrap:anywhere;}
  button {border:0;border-radius:var(--ca-control-radius);background:var(--ca-app-background);color:var(--ca-text);padding:var(--ca-space-2);font:var(--ca-type-label)/var(--ca-leading-body) var(--ca-font-body);}
  button:focus-visible {box-shadow:var(--ca-focus-ring);}
  dialog {border:0;border-radius:var(--ca-control-radius);background:var(--ca-app-background);color:var(--ca-text);padding:var(--ca-space-3);max-width:90vw;max-height:90vh;overflow:auto;}
  dialog img {max-height:78vh;margin-top:var(--ca-space-2);}
</style>
